number1 = input("Enter first number: ")
number2 = input("\nEnter second number: ")
number3 = input("\nEnter third number: ")
sum = float(number1) + float(number2) + float(number3)
print("The sum of {0} and {1} and {2} is {3}".format(number1, number2,number3, sum))
